### ISSUE TITLE
Add Transaction fee Adjustment (Send Confirmation)

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-ios#498]
- [x] after design is ready: https://github.com/horizontalsystems/bank-wallet-ios/issues/250
- [x] after the iPFS data is ready, https://github.com/horizontalsystems/blockchain-meta/issues/48
- [x] get familiar with the requirements from the IPFS team, https://github.com/horizontalsystems/blockchain-meta/issues/48
- [x] note that some blockchains may not have fees at all or the fee may be constant (non chageable). The Send controller should be able to handle such cases.
- [x] implement the hardcoded max/min values for a case when the tx fees are not reachable from the client. Consult with the IPFS team on details.
