### ISSUE TITLE
Send Controller Improvements

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/bank-wallet-ios#52]
**Tasks** 

- [x] Apply new layout
- [x] Send Button should become active when there are no errors:
- when amount is valid (if invalid, display "Balance: xxx" in red)  @Dianaaiym 
- when address is valid (if invalid, display "Incorrect address") @Dianaaiym 
- [x] Exchange Rate
- (if available): all info shown(@TalgatNurdinov provide layout)
- (if not available): don't show rate, don't show base equivalent of fee, make switch inactive(@TalgatNurdinov provide layout)
-- unavailability of ex rate should not prevent user from sending transaction
- [x] add Transaction Confirmation screen (@TalgatNurdinov provide layout). Make sure it shows destination address.
- [x] transaction fee 
- should be obtained from IPFS, 
- if not available use last available fee 
- if that not available we should allow user to enter fee manually (@TalgatNurdinov that options should be considered in the design)

**Comment by esengulov** [comment]
@TalgatNurdinov need a send controller with the balance amount for the coin

**Comment by TalgatNurdinov** [comment]
<img width="1271" alt="screen shot 2018-11-14 at 1 46 07 pm" src="https://user-images.githubusercontent.com/42367908/48467629-ac726180-e813-11e8-8825-e5c84d10c088.png">
 @Dianaaiym
